services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/app
    depends_on:
      - db
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    networks:
      - dev

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easy_db_test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - dev

networks:
  dev:

volumes:
  db_data: